green='\e[1;32m'
NC='\e[0m' # No Color

mkdir -p /usr/local/lib/lv2/caps-ampvts.lv2
mkdir -p /usr/local/lib/lv2/caps-autofilter.lv2
mkdir -p /usr/local/lib/lv2/caps-cabinetii.lv2
mkdir -p /usr/local/lib/lv2/caps-cabinetiii.lv2
mkdir -p /usr/local/lib/lv2/caps-cabinetiv.lv2
mkdir -p /usr/local/lib/lv2/caps-ceo.lv2
mkdir -p /usr/local/lib/lv2/caps-chorusi.lv2
mkdir -p /usr/local/lib/lv2/caps-chorusii.lv2
mkdir -p /usr/local/lib/lv2/caps-click.lv2
mkdir -p /usr/local/lib/lv2/caps-compress.lv2
mkdir -p /usr/local/lib/lv2/caps-compress2x2.lv2
mkdir -p /usr/local/lib/lv2/caps-dirac.lv2
mkdir -p /usr/local/lib/lv2/caps-eq.lv2
mkdir -p /usr/local/lib/lv2/caps-eq2x2.lv2
mkdir -p /usr/local/lib/lv2/caps-jvrev.lv2
mkdir -p /usr/local/lib/lv2/caps-lorenz.lv2
mkdir -p /usr/local/lib/lv2/caps-narrower.lv2
mkdir -p /usr/local/lib/lv2/caps-noisegate.lv2
mkdir -p /usr/local/lib/lv2/caps-pan.lv2
mkdir -p /usr/local/lib/lv2/caps-phaserii.lv2
mkdir -p /usr/local/lib/lv2/caps-plate.lv2
mkdir -p /usr/local/lib/lv2/caps-plate2x2.lv2
mkdir -p /usr/local/lib/lv2/caps-roessler.lv2
mkdir -p /usr/local/lib/lv2/caps-saturate.lv2
mkdir -p /usr/local/lib/lv2/caps-scape.lv2
mkdir -p /usr/local/lib/lv2/caps-sin.lv2
mkdir -p /usr/local/lib/lv2/caps-stereochorusii.lv2
mkdir -p /usr/local/lib/lv2/caps-stereochorusii2x2.lv2
mkdir -p /usr/local/lib/lv2/caps-stereophaserii.lv2
mkdir -p /usr/local/lib/lv2/caps-stereophaserii2x2.lv2
mkdir -p /usr/local/lib/lv2/caps-tonestack.lv2
mkdir -p /usr/local/lib/lv2/caps-white.lv2

cp ampvts.so /usr/local/lib/lv2/caps-ampvts.lv2/ampvts.so
cp autofilter.so /usr/local/lib/lv2/caps-autofilter.lv2/autofilter.so
cp cabinetii.so /usr/local/lib/lv2/caps-cabinetii.lv2/cabinetii.so
cp cabinetiii.so /usr/local/lib/lv2/caps-cabinetiii.lv2/cabinetiii.so
cp cabinetiv.so /usr/local/lib/lv2/caps-cabinetiv.lv2/cabinetiv.so
cp ceo.so /usr/local/lib/lv2/caps-ceo.lv2/ceo.so
cp chorusi.so /usr/local/lib/lv2/caps-chorusi.lv2/chorusi.so
cp chorusii.so /usr/local/lib/lv2/caps-chorusii.lv2/chorusii.so
cp click.so /usr/local/lib/lv2/caps-click.lv2/click.so
cp compress.so /usr/local/lib/lv2/caps-compress.lv2/compress.so
cp compress2x2.so /usr/local/lib/lv2/caps-compress2x2.lv2/compress2x2.so
cp dirac.so /usr/local/lib/lv2/caps-dirac.lv2/dirac.so
cp eq.so /usr/local/lib/lv2/caps-eq.lv2/eq.so
cp eq2x2.so /usr/local/lib/lv2/caps-eq2x2.lv2/eq2x2.so
cp jvrev.so /usr/local/lib/lv2/caps-jvrev.lv2/jvrev.so
cp lorenz.so /usr/local/lib/lv2/caps-lorenz.lv2/lorenz.so
cp narrower.so /usr/local/lib/lv2/caps-narrower.lv2/narrower.so
cp noisegate.so /usr/local/lib/lv2/caps-noisegate.lv2/noisegate.so
cp pan.so /usr/local/lib/lv2/caps-pan.lv2/pan.so
cp phaserii.so /usr/local/lib/lv2/caps-phaserii.lv2/phaserii.so
cp plate.so /usr/local/lib/lv2/caps-plate.lv2/plate.so
cp plate2x2.so /usr/local/lib/lv2/caps-plate2x2.lv2/plate2x2.so
cp roessler.so /usr/local/lib/lv2/caps-roessler.lv2/roessler.so
cp saturate.so /usr/local/lib/lv2/caps-saturate.lv2/saturate.so
cp scape.so /usr/local/lib/lv2/caps-scape.lv2/scape.so
cp sin.so /usr/local/lib/lv2/caps-sin.lv2/sin.so
cp stereochorusii.so /usr/local/lib/lv2/caps-stereochorusii.lv2/stereochorusii.so
cp stereochorusii2x2.so /usr/local/lib/lv2/caps-stereochorusii2x2.lv2/stereochorusii2x2.so
cp stereophaserii.so /usr/local/lib/lv2/caps-stereophaserii.lv2/stereophaserii.so
cp stereophaserii2x2.so /usr/local/lib/lv2/caps-stereophaserii2x2.lv2/stereophaser2x2.so
cp tonestack.so /usr/local/lib/lv2/caps-tonestack.lv2/tonestack.so
cp white.so /usr/local/lib/lv2/caps-white.lv2/white.so

cp ./ttls/ampvts.ttl /usr/local/lib/lv2/caps-ampvts.lv2/ampvts.ttl
cp ./ttls/autofilter.ttl /usr/local/lib/lv2/caps-autofilter.lv2/autofilter.ttl
cp ./ttls/cabinetii.ttl /usr/local/lib/lv2/caps-cabinetii.lv2/cabinetii.ttl
cp ./ttls/cabinetiii.ttl /usr/local/lib/lv2/caps-cabinetiii.lv2/cabinetiii.ttl
cp ./ttls/cabinetiv.ttl /usr/local/lib/lv2/caps-cabinetiv.lv2/cabinetiv.ttl
cp ./ttls/ceo.ttl /usr/local/lib/lv2/caps-ceo.lv2/ceo.ttl
cp ./ttls/chorusi.ttl /usr/local/lib/lv2/caps-chorusi.lv2/chorusi.ttl
cp ./ttls/chorusii.ttl /usr/local/lib/lv2/caps-chorusii.lv2/chorusii.ttl
cp ./ttls/click.ttl /usr/local/lib/lv2/caps-click.lv2/click.ttl
cp ./ttls/compress.ttl /usr/local/lib/lv2/caps-compress.lv2/compress.ttl
cp ./ttls/compress2x2.ttl /usr/local/lib/lv2/caps-compress2x2.lv2/compress2x2.ttl
cp ./ttls/dirac.ttl /usr/local/lib/lv2/caps-dirac.lv2/dirac.ttl
cp ./ttls/eq.ttl /usr/local/lib/lv2/caps-eq.lv2/eq.ttl
cp ./ttls/eq2x2.ttl /usr/local/lib/lv2/caps-eq2x2.lv2/eq2x2.ttl
cp ./ttls/jvrev.ttl /usr/local/lib/lv2/caps-jvrev.lv2/jvrev.ttl
cp ./ttls/lorenz.ttl /usr/local/lib/lv2/caps-lorenz.lv2/lorenz.ttl
cp ./ttls/narrower.ttl /usr/local/lib/lv2/caps-narrower.lv2/narrower.ttl
cp ./ttls/noisegate.ttl /usr/local/lib/lv2/caps-noisegate.lv2/noisegate.ttl
cp ./ttls/pan.ttl /usr/local/lib/lv2/caps-pan.lv2/pan.ttl
cp ./ttls/phaserii.ttl /usr/local/lib/lv2/caps-phaserii.lv2/phaserii.ttl
cp ./ttls/plate.ttl /usr/local/lib/lv2/caps-plate.lv2/plate.ttl
cp ./ttls/plate2x2.ttl /usr/local/lib/lv2/caps-plate2x2.lv2/plate2x2.ttl
cp ./ttls/roessler.ttl /usr/local/lib/lv2/caps-roessler.lv2/roessler.ttl
cp ./ttls/saturate.ttl /usr/local/lib/lv2/caps-saturate.lv2/saturate.ttl
cp ./ttls/scape.ttl /usr/local/lib/lv2/caps-scape.lv2/scape.ttl
cp ./ttls/sin.ttl /usr/local/lib/lv2/caps-sin.lv2/sin.ttl
cp ./ttls/stereochorusii.ttl /usr/local/lib/lv2/caps-stereochorusii.lv2/stereochorusii.ttl
cp ./ttls/stereochorusii2x2.ttl /usr/local/lib/lv2/caps-stereochorusii2x2.lv2/stereochorusii2x2.ttl
cp ./ttls/stereophaserii.ttl /usr/local/lib/lv2/caps-stereophaserii.lv2/stereophaserii.ttl
cp ./ttls/stereophaserii2x2.ttl /usr/local/lib/lv2/caps-stereophaserii2x2.lv2/stereophaser2x2.ttl
cp ./ttls/tonestack.ttl /usr/local/lib/lv2/caps-tonestack.lv2/tonestack.ttl
cp ./ttls/white.ttl /usr/local/lib/lv2/caps-white.lv2/white.ttl

cp ./ttls/manifest.ampvts /usr/local/lib/lv2/caps-ampvts.lv2/manifest.ttl
cp ./ttls/manifest.autofilter /usr/local/lib/lv2/caps-autofilter.lv2/manifest.ttl
cp ./ttls/manifest.cabinetii /usr/local/lib/lv2/caps-cabinetii.lv2/manifest.ttl
cp ./ttls/manifest.cabinetiii /usr/local/lib/lv2/caps-cabinetiii.lv2/manifest.ttl
cp ./ttls/manifest.cabinetiv /usr/local/lib/lv2/caps-cabinetiv.lv2/manifest.ttl
cp ./ttls/manifest.ceo /usr/local/lib/lv2/caps-ceo.lv2/manifest.ttl
cp ./ttls/manifest.chorusi /usr/local/lib/lv2/caps-chorusi.lv2/manifest.ttl
cp ./ttls/manifest.chorusii /usr/local/lib/lv2/caps-chorusii.lv2/manifest.ttl
cp ./ttls/manifest.click /usr/local/lib/lv2/caps-click.lv2/manifest.ttl
cp ./ttls/manifest.compress /usr/local/lib/lv2/caps-compress.lv2/manifest.ttl
cp ./ttls/manifest.compress2x2 /usr/local/lib/lv2/caps-compress2x2.lv2/manifest.ttl
cp ./ttls/manifest.dirac /usr/local/lib/lv2/caps-dirac.lv2/manifest.ttl
cp ./ttls/manifest.eq /usr/local/lib/lv2/caps-eq.lv2/manifest.ttl
cp ./ttls/manifest.eq2x2 /usr/local/lib/lv2/caps-eq2x2.lv2/manifest.ttl
cp ./ttls/manifest.jvrev /usr/local/lib/lv2/caps-jvrev.lv2/manifest.ttl
cp ./ttls/manifest.lorenz /usr/local/lib/lv2/caps-lorenz.lv2/manifest.ttl
cp ./ttls/manifest.narrower /usr/local/lib/lv2/caps-narrower.lv2/manifest.ttl
cp ./ttls/manifest.noisegate /usr/local/lib/lv2/caps-noisegate.lv2/manifest.ttl
cp ./ttls/manifest.pan /usr/local/lib/lv2/caps-pan.lv2/manifest.ttl
cp ./ttls/manifest.phaserii /usr/local/lib/lv2/caps-phaserii.lv2/manifest.ttl
cp ./ttls/manifest.plate /usr/local/lib/lv2/caps-plate.lv2/manifest.ttl
cp ./ttls/manifest.plate2x2 /usr/local/lib/lv2/caps-plate2x2.lv2/manifest.ttl
cp ./ttls/manifest.roessler /usr/local/lib/lv2/caps-roessler.lv2/manifest.ttl
cp ./ttls/manifest.saturate /usr/local/lib/lv2/caps-saturate.lv2/manifest.ttl
cp ./ttls/manifest.scape /usr/local/lib/lv2/caps-scape.lv2/manifest.ttl
cp ./ttls/manifest.sin /usr/local/lib/lv2/caps-sin.lv2/manifest.ttl
cp ./ttls/manifest.stereochorusii /usr/local/lib/lv2/caps-stereochorusii.lv2/manifest.ttl
cp ./ttls/manifest.stereochorusii2x2 /usr/local/lib/lv2/caps-stereochorusii2x2.lv2/manifest.ttl
cp ./ttls/manifest.stereophaserii /usr/local/lib/lv2/caps-stereophaserii.lv2/manifest.ttl
cp ./ttls/manifest.stereophaserii2x2 /usr/local/lib/lv2/caps-stereophaserii2x2.lv2/manifest.ttl
cp ./ttls/manifest.tonestack /usr/local/lib/lv2/caps-tonestack.lv2/manifest.ttl
cp ./ttls/manifest.white /usr/local/lib/lv2/caps-white.lv2/manifest.ttl
